// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXyph5ZjGHwQYsPADYNYRPKWRfhEdXIM',
    appId: '1:412999685810:android:216786a6982659e3ccdbab',
    messagingSenderId: '412999685810',
    projectId: 'ditonton-final-submissio-a8b0c',
    storageBucket: 'ditonton-final-submissio-a8b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRV5jHOIVOjnZdvSwpkTOT4Ni4WFvl-o',
    appId: '1:412999685810:ios:826efe9cb1de1c97ccdbab',
    messagingSenderId: '412999685810',
    projectId: 'ditonton-final-submissio-a8b0c',
    storageBucket: 'ditonton-final-submissio-a8b0c.appspot.com',
    iosClientId: '412999685810-dv7a177653r2t9bdnir6tk631tfacu0v.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
